name: CI

on:
    pull_request:
      branches:
        - '**'

jobs:
    micro_ros_demos:
        runs-on: ubuntu-20.04
        container: microros/base:rolling
        defaults:
          run:
            shell: bash

        steps:
        - name: Download environment
          run: |
            cd /uros_ws
            apt update
            rosdep update
            source /opt/ros/rolling/setup.bash
            source install/local_setup.bash
            rosdep update
            ros2 run micro_ros_setup create_firmware_ws.sh host
            rm -rf src/uros/micro-ROS-demos
        - uses: actions/checkout@v2
          with:
            path: uros_ws/src/uros/micro-ROS-demos
        - name: Build
          run: |
            cd /uros_ws
            source /opt/ros/rolling/setup.bash
            source install/local_setup.bash
            ros2 run micro_ros_setup build_firmware.sh
